import { getAllPosts } from "@utils/mdx/posts";
import Head from "next/head";
import Link from "next/link";

import type { Items } from "@custom-types/posts";

import styles from "../styles/Home.module.css";

export async function getStaticProps() {
  const posts = getAllPosts([
    "slug",
    "date",
    "thumbnail",
    "title",
    "description",
  ]);

  return { props: { posts } };
}

type HomeProps = {
  posts: Items[];
};

export default function Home({ posts }: HomeProps) {
  console.log(posts);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Articles</h1>
        {posts.map((post) =>
          post.type === "article" ? (
            <Link key={post.slug} href="/[slug]" as={`/${post.slug}`}>
              <h2>{post.title}</h2>
            </Link>
          ) : (
            <article>
              <h1>{post.title}</h1>
            </article>
          )
        )}
      </main>
    </div>
  );
}
